name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.5.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: eu-north-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform destroy
      run: terraform destroy -auto-approve
